Use retrieve-dir to retrieve plugins

diff --git a/hooks/install-plugin/10 b/hooks/install-plugin/10
--- a/hooks/install-plugin/10
+++ b/hooks/install-plugin/10
@@ -4,25 +4,30 @@ set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x
 remote=$1
 target=$2
 
-git clone $remote "$PLUSHU_PLUGINS_DIR/$target"
+target_dir=$PLUSHU_PLUGINS_DIR/$target
 
-# When installing as root, give the plushu user ownership of everything
-# within the newly-cloned plugin
-if [[ "$EUID" == 0 ]]; then
-  chown -R "$PLUSHU_USER:" "$PLUSHU_PLUGINS_DIR/$target"
-fi
+# If the plugin doesn't already exist
+if [[ ! -e "$target_dir" ]]; then
 
-# If the newly-cloned plugin has an install script
-if [[ -f "$PLUSHU_PLUGINS_DIR/$target/install" ]]; then
+  # Retrieve it
+  "$PLUSHU_ROOT/lib/plushook" retrieve-dir "$target_dir" "$remote"
 
-  # We don't test for executable status, we just
-  # let the shell fail if the install script isn't set executable
-  PLUSHU_PLUGIN_NAME="$target" \
-  PLUSHU_PLUGIN_PATH="$PLUSHU_PLUGINS_DIR/$target" \
-    "$PLUSHU_PLUGINS_DIR/$target/install"
+  # If the plugin was not downloaded
+  if [[ ! -e "$target_dir" ]]; then
+    echo "URL could not be retrieved: $remote" >&2
+    exit 1
 
-else
-  # Notify that the plugin has been installed
-  # in lieu of a more complex
-  echo "Plugin '$target' installed."
+  # If the newly-cloned plugin has an install script
+  elif [[ -f "$PLUSHU_PLUGINS_DIR/$target/install" ]]; then
+
+    # We don't test for executable status, we just
+    # let the shell fail if the install script isn't set executable
+    PLUSHU_PLUGIN_NAME="$target" PLUSHU_PLUGIN_PATH="$target_dir" \
+      "$target_dir/install"
+
+  else
+    # Notify that the plugin has been installed
+    # in lieu of a more complex
+    echo "Plugin '$target' installed."
+  fi
 fi
